// <auto-generated />
namespace BlogDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DeltedComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeltedComments));
        
        string IMigrationMetadata.Id
        {
            get { return "202004161957024_DeltedComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
